### ISSUE TITLE
Copying shell commands wraps them in Rust code

### ISSUE THREAD

**Issue by Prof-Bloodstone** [avr-rust/book.avr-rust.com#36]
When copying shell commands, like for example here: https://book.avr-rust.com/003-building-a-crate-for-avr.html#compiling-a-crate
I'd expect to have this line in my clipboard:
```sh
cargo build -Z build-std=core --target avr-unknown-gnu-atmega328 --release
```
Instead, I get:
```rust

#![allow(unused)]
fn main() {
cargo build -Z build-std=core --target avr-unknown-gnu-atmega328 --release
}
```

**Comment by stappersg** [comment]
Fixed in commit 2a89941, @Prof-Bloodstone thanks for reporting.
