### ISSUE TITLE
Add a "known working Rust nightly" version to 002.1

### ISSUE THREAD

**Issue by gergoerdi** [avr-rust/book.avr-rust.com#37]
I have just discovered that [the latest Nightly snapshot of Rust doesn't work with the AVR backend](https://github.com/rust-lang/rust/issues/88252). In 002.1, instead of just saying "use the nightly channel", it would be useful to have a specific "known-to-work" nightly version "pinned".

**Comment by gergoerdi** [comment]
@stappersg https://book.avr-rust.com/002-installing-the-compiler.html still says to use the nightly channel... so which is the "blessed" version?

**Comment by stappersg** [comment]
Nightly a.k.a. recent.    So surely not a pin-down to a particular version.
