### ISSUE TITLE
Updating/deploying the book causing a ~10+ minute outage whilst GitHub builds it

### ISSUE THREAD

**Issue by dylanmckay** [avr-rust/book.avr-rust.com#6]
The files are already HTML so I don't know what's going on. The book goes completely offline after a push for a bit. At the time of posting this issue, it is down.

**Comment by asaaki** [comment]
I think this time it seems to be a permanent 404, tried to reload for half an hour or so.

**Comment by shepmaster** [comment]
Yes, the top-level domain doesn't seem correctly set up.

For now, you can go to https://avr-rust.github.io/book.avr-rust.com/

**Comment by shepmaster** [comment]
@dylanmckay I updated the repo's settings:

![image](https://user-images.githubusercontent.com/174509/88394330-45010900-cd8d-11ea-9e59-e31d2eb6d99b.png)

Seems to be working again.

**Comment by dylanmckay** [comment]
I am about to redeploy, we will see how it goes :crossed_fingers:

**Comment by dylanmckay** [comment]
Deployed from fb0daf9...09d2122

**Comment by dylanmckay** [comment]
Triggers an outage

![book-404](https://user-images.githubusercontent.com/7722159/88450173-2ab84f80-cea1-11ea-9464-7417d15b609b.png)

**Comment by dylanmckay** [comment]
![gh-pages-settings](https://user-images.githubusercontent.com/7722159/88450207-5c311b00-cea1-11ea-815f-5b2e28242bb1.png)

I think I know what is happening - the CNAME file that is committed by setting up the custom domain is lost by the deploy script.

**Comment by dylanmckay** [comment]
Fixed in 288067c9c04064753cf467065334c8f2ff3a5446.

**Comment by dylanmckay** [comment]
Redeploying now to test outage

**Comment by dylanmckay** [comment]
Deployed 614402a...92d011d

**Comment by dylanmckay** [comment]
No more outage during deployment time, nice.
