### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by shepmaster** [avr-rust/book.avr-rust.com#8]
I'm no lawyer, but I understand that it's generally better to say that the prose is licensed by creative commons and the code is MIT. Something we may want to do sooner rather than later.

**Comment by dylanmckay** [comment]
Agree

**Comment by dylanmckay** [comment]
Do we choose a creative commons license with the ShareAlike clause? It would seem like a good idea

> Attribution-ShareAlike
> CC BY-SA
> 
> This license lets others remix, adapt, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects.

Or perhaps another variant of creative commons license

**Comment by shepmaster** [comment]
For the omnibus, I chose http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by dylanmckay** [comment]
Fixed in 3a2c8f857992a2d1d1a8ee96efd1b1b7bc5abc04
